CarritoCompras/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarritoCompras.Models;

namespace CarritoCompras.Controllers
{
    public class CarritoController : Controller
    {
        //
        // GET: /Carrito/
        private CarritoBDEntities ce = new CarritoBDEntities();

        public ActionResult AgregaCarrito(int id)
        {
            if (Session["carrito"] == null)
            {
                List<CarritoItem> compras = new List<CarritoItem>();
                compras.Add(new CarritoItem(ce.Producto.Find(id),1));
                Session["carrito"] = compras;
            }
            else
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
                int IndexExistente = getIndex(id);
                if (IndexExistente == -1)
                    compras.Add(new CarritoItem(ce.Producto.Find(id), 1));
                else
                    compras[IndexExistente].Cantidad++;
                Session["carrito"] = compras;
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            compras.RemoveAt(getIndex(id));
            Session["carrito"] = compras;
            return View("AgregaCarrito");
        }

        private int getIndex(int id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            for (int i = 0; i < compras.Count; i++)
            {
                if (compras[i].Producto.Id == id)
                    return i;
            }
            return -1;
        }

    }
}

CarritoCompras/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarritoCompras.Models;
using CarritoCompras.Models;

namespace CarritoCompras.Controllers
{
    public class ProductoController : Controller
    {
        //
        // GET: /Producto/

        private CarritoBDEntities ce = new CarritoBDEntities();

        public ActionResult Index()
        {

            return View(ce.Producto.ToList().OrderBy(x=>x.Nombre));
        }

    }
}

CarritoCompras/Views/Carrito/AgregaCarrito.cshtml
@{
    ViewBag.Title = "AgregaCarrito";
}

<h2>Mi Carrito de Compras</h2>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            double total = 0;
        }
        @if (Session["carrito"] != null)
        {
            
            foreach (var item in (List<CarritoCompras.Models.CarritoItem>)Session["carrito"])
            {
                total += (double)(item.Cantidad * item.Producto.Precio);
                <tr>
                    <td>@item.Producto.Id</td>
                    <td>@item.Producto.Nombre</td>
                    <td>@String.Format("{0:C}",item.Producto.Precio)</td>
                    <td>@item.Cantidad</td>
                    <td>@String.Format("{0:C}",(item.Cantidad*item.Producto.Precio))</td>
                    <td>@Html.ActionLink("Eliminar","Delete","Carrito",new {Id=item.Producto.Id },null)</td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <th colspan="4">Total</th>
            <th>@String.Format("{0:c}",total)</th>
        </tr>
    </tfoot>
</table>
@Html.ActionLink("Seguir Comprando", "Index", "Producto", null, null)